uploads = []
outputs = []

[[generated]]
id = "5ukTdeuxW_wiCo65yu9o_"
uri = "file://artifacts/xbrainpro-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tdMEF44aXmME3wFpNhE0B"
uri = "file://artifacts/mockup-sandbox/public/images/neura-city-street.png"
type = "image"
title = "street view neura city"

[[generated]]
id = "hC7c7pkPreNJh0QDt10hy"
uri = "file://artifacts/mockup-sandbox/public/images/neura-city-npc.png"
type = "image"
title = "npc view neura city"

[[generated]]
id = "Ll1GGfdvcaMGQ6sRIoyBp"
uri = "file://artifacts/mockup-sandbox/public/images/neura-lux-bg.png"
type = "image"
title = "Luxurious neon-gold night city skyline"

[[generated]]
id = "CuAorSJiY3u5DImMgEQLy"
uri = "file://artifacts/mockup-sandbox/public/images/neura-lux-avatar.png"
type = "image"
title = "Fashionable polished 3D avatar hero"

[[generated]]
id = "ScpZVinWN7dCLIgVrXa7t"
uri = "file://artifacts/mockup-sandbox/public/images/neura-neon-bg-login.png"
type = "image"
title = "Neon city background"

[[generated]]
id = "iH3n9QfPHNR69_T4ml8iO"
uri = "file://artifacts/mockup-sandbox/public/images/neura-neon-avatar.png"
type = "image"
title = "Neon 3D game avatar"

[[generated]]
id = "QENkfMRFMbIv0pyVltnys"
uri = "file://artifacts/mockup-sandbox/public/images/neura-neon-bg-lobby.png"
type = "image"
title = "Dark neon lobby background"

[[generated]]
id = "GmoBd8P1JSWrr8UwlawIb"
uri = "file://artifacts/mockup-sandbox/public/images/neura-soft-bg.png"
type = "image"
title = "Pastel city at golden hour"

[[generated]]
id = "JPnJiTfkAlEDER_-G1V3L"
uri = "file://artifacts/mockup-sandbox/public/images/neura-soft-avatar.png"
type = "image"
title = "Cute 3D chibi game avatar"

[[generated]]
id = "ULmeeyJY4eCZcIWVMgfn2"
uri = "file://artifacts/mockup-sandbox/public/images/ng-login-bg.png"
type = "image"
title = "Neon city skyline background"

[[generated]]
id = "1qwsL9VFH8Ds-DkKNXiCv"
uri = "file://artifacts/mockup-sandbox/public/images/ng-lobby-bg.png"
type = "image"
title = "panoramic neon city background"

[[generated]]
id = "NjbOZ4b8xED_s4kvGKzOj"
uri = "file://artifacts/mockup-sandbox/public/images/ng-resdl-bg.png"
type = "image"
title = "Neon game wide background"

[[generated]]
id = "e6HTdqHc_69lNtekakywd"
uri = "file://artifacts/mockup-sandbox/public/images/ng-loading-bg.png"
type = "image"
title = "Neon city wide background"

[[generated]]
id = "RdvLTDVntjad7LWm7eYJ4"
uri = "file://artifacts/mockup-sandbox/public/images/ng-map-city-bg.png"
type = "image"
title = "isometric neon city map"

[[generated]]
id = "nOeUZ4-ARR_TIhgUP9Moz"
uri = "file://artifacts/mockup-sandbox/public/images/ng-ingame-bg.png"
type = "image"
title = "neon cyberpunk city street gameplay"

[[generated]]
id = "dwOqBbHV7RQ5kJjXCJm0Y"
uri = "file://artifacts/mockup-sandbox/public/images/ng-ingame-minimap.png"
type = "image"
title = "minimap view"

[[generated]]
id = "R6ZpoAAjXH41YWFb1nibf"
uri = "file://artifacts/mockup-sandbox/public/images/ng-mapdl-bg.png"
type = "image"
title = "Neon city map loading background"

[[generated]]
id = "I1D9WRriSHt6o-_ApcgDr"
uri = "file://artifacts/mockup-sandbox/public/images/ng-terms-bg.png"
type = "image"
title = "Neon cyber city terms background"

[[generated]]
id = "59D25lvqMVobb2nbxcVNa"
uri = "file://artifacts/mockup-sandbox/public/images/ng-custom-bg.png"
type = "image"
title = "neon customization room background"

[[generated]]
id = "ANTWCfwnmQuYYPEWMWEhw"
uri = "file://artifacts/mockup-sandbox/public/images/ng-charsel-bg.png"
type = "image"
title = "Neon cyberpunk game lobby background"

[[generated]]
id = "R9Qd1mJhhoaNQPPE5QjhM"
uri = "file://artifacts/mockup-sandbox/public/images/ng-charsel-male.png"
type = "image"
title = "3D male neon cyberpunk character"

[[generated]]
id = "nX7T8wdvSycWiTpQYS5ba"
uri = "file://artifacts/mockup-sandbox/public/images/ng-charsel-female.png"
type = "image"
title = "3D female neon cyberpunk character"

[[generated]]
id = "jctDm-FiMH_xnTac0gNMQ"
uri = "file://artifacts/mockup-sandbox/public/images/ng-name-bg.png"
type = "image"
title = "Neon game background"
