// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/neura-city/ChatOverlay.tsx": () => import("../components/mockups/neura-city/ChatOverlay.tsx"),
  "./components/mockups/neura-city/TalkPrompt.tsx": () => import("../components/mockups/neura-city/TalkPrompt.tsx"),
  "./components/mockups/neura-city/WorldView.tsx": () => import("../components/mockups/neura-city/WorldView.tsx")
};
